In [13]:
import tensorflow as tf
from cleverhans.tf2.attacks.fast_gradient_method import fast_gradient_method
import matplotlib.pyplot as plt
import numpy as np
from keras.models import load_model
from PreprocessTool import getImage_wellClassified

In [14]:
 #获取模型分类正确的图像数据
labelName,imgs,imgData,predictions,count=getImage_wellClassified(10,"ImageNet")
model=tf.keras.applications.resnet50.ResNet50(weights='imagenet')
max_index = np.argmax(predictions, axis=1)
#对抗样本的最大最小值
clip_min =np.array([-103.939, -116.779, -123.68],dtype="float32")
clip_max =np.array( [255 - 103.939, 255 - 116.779, 255 - 123.68],dtype="float32")


val_id:4254, ILSVRC_ID:614, WIND:n01978455
val_id:30077, ILSVRC_ID:583, WIND:n03075370
val_id:48048, ILSVRC_ID:937, WIND:n03866082
val_id:1667, ILSVRC_ID:494, WIND:n01629819
val_id:30741, ILSVRC_ID:360, WIND:n09468604
val_id:13831, ILSVRC_ID:223, WIND:n02672831
val_id:34367, ILSVRC_ID:725, WIND:n03459775
val_id:5894, ILSVRC_ID:629, WIND:n02190166
val_id:45013, ILSVRC_ID:596, WIND:n03933933
val_id:20188, ILSVRC_ID:922, WIND:n03733281
1/1 [==============================] - 2s 2s/step
分类准确率: 0.7
分类成功图片数量: 7


In [15]:
ground_truth = np.zeros_like(predictions)
ground_truth[np.arange(len(predictions)), max_index] = 1
ground_truth

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [16]:
tf.stack(imgData)

<tf.Tensor: shape=(7, 224, 224, 3), dtype=float32, numpy=
array([[[[ -74.939     ,  -98.779     , -103.68      ],
         [ -82.939     , -106.779     , -111.68      ],
         [ -69.939     ,  -95.779     , -100.68      ],
         ...,
         [ -55.939003  ,  -78.779     ,  -92.68      ],
         [ -67.939     ,  -86.779     , -106.68      ],
         [ -64.939     ,  -84.779     , -100.68      ]],

        [[ -59.939003  ,  -85.779     ,  -90.68      ],
         [ -76.939     , -102.779     , -107.68      ],
         [ -71.939     ,  -97.779     , -102.68      ],
         ...,
         [ -56.939003  ,  -79.779     ,  -93.68      ],
         [ -54.939003  ,  -75.779     ,  -95.68      ],
         [ -64.939     ,  -86.779     , -102.68      ]],

        [[ -70.939     ,  -96.779     , -101.68      ],
         [ -79.939     , -105.779     , -110.68      ],
         [ -73.939     ,  -97.779     , -102.68      ],
         ...,
         [ -66.939     ,  -89.779     , -103.68      ],


In [17]:

img_adv=fast_gradient_method(model_fn=model,
                                x=tf.stack(imgData),
                                eps=0.1,norm=2,
                                clip_min=clip_min,clip_max=clip_max,
                                targeted=None,
                                sanity_checks=False)

In [19]:
img_adv[0]

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ -74.93845  ,  -98.777664 , -103.67947  ],
        [ -82.93841  , -106.77766  , -111.67938  ],
        [ -69.93885  ,  -95.778465 , -100.67993  ],
        ...,
        [ -55.938847 ,  -78.77861  ,  -92.679726 ],
        [ -67.93887  ,  -86.77868  , -106.67978  ],
        [ -64.93892  ,  -84.77883  , -100.679955 ]],

       [[ -59.938824 ,  -85.77828  ,  -90.67993  ],
        [ -76.938805 , -102.77857  , -107.680016 ],
        [ -71.93902  ,  -97.77929  , -102.68032  ],
        ...,
        [ -56.93901  ,  -79.7789   ,  -93.67984  ],
        [ -54.939037 ,  -75.77891  ,  -95.67986  ],
        [ -64.93902  ,  -86.779015 , -102.68001  ]],

       [[ -70.93826  ,  -96.77737  , -101.6791   ],
        [ -79.93896  , -105.77892  , -110.68011  ],
        [ -73.93945  ,  -97.78054  , -102.68104  ],
        ...,
        [ -66.939255 ,  -89.77942  , -103.68004  ],
        [ -69.93917  ,  -93.779175 , -108.68003  ],
        [ -78.9390